# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=99999"]  # blockt versehentlich >95MB
    - id: end-of-file-fixer
    - id: trailing-whitespace
