# Globale Domänenparameter (werden im Bot/Backend referenziert)
time_zone: Europe/Zurich
units:
  price: CHF/kWh
  energy: kWh
  energy_large: MWh
caps:
  max_event_hours_paid: 3.0
  max_participation_rate: 0.629   # 62.9%
  max_offer_pct_of_month: 62.9    # %
device_defaults:
  dishwasher:
    cycle_kwh: 1.44
    cycle_hours: 1.5
compensation:
  base_comp_chf_kwh: 0.29
naming:
  regulation_price_label: TRE     # tre_price_chf_kwh
